### PR TITLE
 Sprint 1 - automating variant_workbook_parser and slack notifications

### PR DESCRIPTION
**Pull request by RSWilson1**
The purpose of this workflow is to automate the parsing of variant workbooks and eventually the submission of variants to ClinVar. The workflow runs in a docker container using Nextflow. It has a configuration file which is used to set the variables and can be changed for production. In production this will be added to the crontab file for running daily.

- Created dockerfile for running nextflow pipeline
- Nextflow pipeline to run variant_workbook_parser
- script for slack notifications using webhooks

Current notification style for successful parsing:
image
Current notification style for fail of workbook parsing:
image

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/2)

### CODE REVIEW

**Review by RSWilson1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/2)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @kjwinfield)

___
*[`dockerfile` line 68 at r2](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/2#-O5OK0kd-OZaYDtrOinX:-O5OK0ke8VwBL5gPNHJO:b-hmo8tc) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/cab0b37a1acdfffd7393a47ce27285e0c15e05ca/dockerfile#L68)):*
> ```
> 
> # Specify the entrypoint to ensure the virtual environment is activated
> ENTRYPOINT ["nextflow", "run", "/home/main.nf", "-c", "/home/configurations/test_config_20240821.txt"]
> ```

Hard-coded, I was wondering if there was a better way to do this, without explicitly naming the config, although I could use a more generic production name so that it doesn't require changing name each time.

**Review by kjwinfield — CHANGES_REQUESTED** [review]
> Reviewed 8 of 11 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/2)* status: all files reviewed, 12 unresolved discussions (waiting on @RSWilson1)

___
*[`dockerfile` line 68 at r2](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/2#-O5O6r7-0esLbXh7insd:-O5O6r7-0esLbXh7inse:bfjr6bk) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/cab0b37a1acdfffd7393a47ce27285e0c15e05ca/dockerfile#L68)):*
> ```
> 
> # Specify the entrypoint to ensure the virtual environment is activated
> ENTRYPOINT ["nextflow", "run", "/home/main.nf", "-c", "/home/configurations/test_config_20240821.txt"]
> ```

should the test config be hard coded like this?
___
*[`main.nf` line 37 at r4](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/2#-O5Od__8B8NNqsEN6SWf:-O5Od__8B8NNqsEN6SWg:b-whgpff) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/d4e50cf4fc7cb08977bf29b13cb3da38f1634ae9/main.nf#L37)):*
> ```Nextflow
>         """
>         cp /variant_workbook_parser/parser_config.json ./parser_config.json
>         if ${cmd} --no_dx_upload; then
> ```

not sure if i understand this if then loop (sorry)
is this saying that if command is no dx upload + testing = success
but if dxupload + testing = failure
if so, why?
___
*[`README.md` line 20 at r4](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/2#-O5Oc35vB4YQQkdkcG-D:-O5Oc35vB4YQQkdkcG-E:b-r47iw) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/d4e50cf4fc7cb08977bf29b13cb3da38f1634ae9/README.md#L20)):*
> ```Markdown
> This repository contains a Nextflow workflow designed to parse variant workbooks.
> The workflow is configured to run both locally and in a production environment.
> The production environment runs in a docker container ().
> ```

are these () supposed to have something in
___
*[`tests/test_notifications.py` line 26 at r4](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/2#-O5OcLpwAakW9WJm86KW:-O5OcLpwAakW9WJm86KX:bmhtjc7) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/d4e50cf4fc7cb08977bf29b13cb3da38f1634ae9/tests/test_notifications.py#L26)):*
> ```Python
> 
> 
> class TestSlackNotifications(unittest.TestCase):
> ```

could you add some docstrings please?
___
*[`tests/test_notifications.py` line 26 at r4](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/2#-O5OdBLe01t5GIZeuSxM:-O5OdBLe01t5GIZeuSxN:b-bfqvp5) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/d4e50cf4fc7cb08977bf29b13cb3da38f1634ae9/tests/test_notifications.py#L26)):*
> ```Python
> 
> 
> class TestSlackNotifications(unittest.TestCase):
> ```

you've also a bunch of lines to long errors here but not essential to fix if you don't want to 
___
*[`utils/slack_notifications.py` line 40 at r2](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/2#-O5NXqcA-InUC58iEP6y:-O5NXqcA-InUC58iEP6z:b-yysq5r) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/cab0b37a1acdfffd7393a47ce27285e0c15e05ca/utils/slack_notifications.py#L40)):*
> ```Python
>     """
>     parser = argparse.ArgumentParser(
>         description="Monitor jobs launched by eggd_conductor"
> ```

looks like this was copied from some other script and should be changed/deleted
___
*[`utils/slack_notifications.py` line 279 at r2](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/2#-O5OEIKC0pwkbfTZclq8:-O5OEIKC0pwkbfTZclq9:bpw8e4i) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/cab0b37a1acdfffd7393a47ce27285e0c15e05ca/utils/slack_notifications.py#L279)):*
> ```Python
> 
>     if parsed_args.testing:
>         script_name = ':mailbox:automated-workbook-parsing - Testing :test_tube:'
> ```

could you add a space between :mailbox: and automated-... to make consistent with other messages
___
*[`utils/slack_notifications.py` line 281 at r2](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/2#-O5OEWjkBtQJEdDMlRqH:-O5OEWjkBtQJEdDMlRqI:bnj7hl0) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/cab0b37a1acdfffd7393a47ce27285e0c15e05ca/utils/slack_notifications.py#L281)):*
> ```Python
>         script_name = ':mailbox:automated-workbook-parsing - Testing :test_tube:'
>     else:
>         script_name = ':mailbox:automated-workbook-parsing'
> ```

same as above
___
*[`utils/slack_notifications.py` line 283 at r2](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/2#-O5OEktU8g0q-Kfm7GGs:-O5OEktU8g0q-Kfm7GGt:b-mbn7np) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/cab0b37a1acdfffd7393a47ce27285e0c15e05ca/utils/slack_notifications.py#L283)):*
> ```Python
>         script_name = ':mailbox:automated-workbook-parsing'
>     # Chnage webhook URL depending on the channel
>     if parsed_args.channel == 'egg-test':
> ```

do we need args.testing and args.channel?
could we say if args.channel = egg-test then add the Testing :test_tube: flag
___
*[`utils/slack_notifications.py` line 299 at r2](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/2#-O5NYZqv7y4UR8nFL5FT:-O5NYZqv7y4UR8nFL5FU:b-87xi76) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/cab0b37a1acdfffd7393a47ce27285e0c15e05ca/utils/slack_notifications.py#L299)):*
> ```Python
>             message = (
>                 f"{script_name}\n"
>                 f"Automated parsing has sucessfully run.\n"
> ```

typo successfully
___
*[`utils/slack_notifications.py` line 308 at r4](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/2#-O5Ocsj5Eal8NL7vQz5o:-O5Ocsj5Eal8NL7vQz5p:bnj7hl0) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/d4e50cf4fc7cb08977bf29b13cb3da38f1634ae9/utils/slack_notifications.py#L308)):*
> ```Python
>             message = (
>                 f"{script_name}\n"
>                 f"Automated parsing has sucessfully run.\n"
> ```

same as above

**Review by RSWilson1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/2)* status: 6 of 11 files reviewed, 12 unresolved discussions (waiting on @kjwinfield)

___
*[`dockerfile` line 68 at r2](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/2#-O5O6r7-0esLbXh7insd:-O5TQrt10YeScD2PoEY7:btmma8q) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/cab0b37a1acdfffd7393a47ce27285e0c15e05ca/dockerfile#L68)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

should the test config be hard coded like this?
</blockquote></details>

Nope, that's what I was mentioning, I have since worked out a way to provide the config in the docker run command. So will remove entry point.
___
*[`main.nf` line 37 at r4](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/2#-O5Od__8B8NNqsEN6SWf:-O5TRMy12o-MylOzSLCs:bl0fb1r) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/d4e50cf4fc7cb08977bf29b13cb3da38f1634ae9/main.nf#L37)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

not sure if i understand this if then loop (sorry)
is this saying that if command is no dx upload + testing = success
but if dxupload + testing = failure
if so, why?
</blockquote></details>

This works as if [script]; then success script else fail script. So it should only run if the script completes successfully otherwise an error is raised and the else statement is run instead. Does that make sense?
___
*[`README.md` line 20 at r4](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/2#-O5Oc35vB4YQQkdkcG-D:-O5TK8ah6bYq-hdAP_uq:brpmqc3) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/d4e50cf4fc7cb08977bf29b13cb3da38f1634ae9/README.md#L20)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

are these () supposed to have something in
</blockquote></details>

removed.
___
*[`tests/test_notifications.py` line 26 at r4](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/2#-O5OcLpwAakW9WJm86KW:-O5Tq5u40Mxrp79kQP_q:b-7tfmjp) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/d4e50cf4fc7cb08977bf29b13cb3da38f1634ae9/tests/test_notifications.py#L26)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

could you add some docstrings please?
</blockquote></details>

added
___
*[`tests/test_notifications.py` line 26 at r4](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/2#-O5OdBLe01t5GIZeuSxM:-O5XlbFe1ruquu61dUx_:b-m16y8f) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/d4e50cf4fc7cb08977bf29b13cb3da38f1634ae9/tests/test_notifications.py#L26)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

you've also a bunch of lines to long errors here but not essential to fix if you don't want to
</blockquote></details>

I have shortened some of them
___
*[`utils/slack_notifications.py` line 40 at r2](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/2#-O5NXqcA-InUC58iEP6y:-O5TKArgB6CxsfwLyxTr:b1vq9ci) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/cab0b37a1acdfffd7393a47ce27285e0c15e05ca/utils/slack_notifications.py#L40)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

looks like this was copied from some other script and should be changed/deleted
</blockquote></details>

Updated to the correct description.
___
*[`utils/slack_notifications.py` line 279 at r2](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/2#-O5OEIKC0pwkbfTZclq8:-O5TLl5i0IYZlH-Trg1K:bb7f2mf) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/cab0b37a1acdfffd7393a47ce27285e0c15e05ca/utils/slack_notifications.py#L279)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

could you add a space between :mailbox: and automated-... to make consistent with other messages
</blockquote></details>

done
___
*[`utils/slack_notifications.py` line 281 at r2](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/2#-O5OEWjkBtQJEdDMlRqH:-O5TLm0w3FqEJN4s3-ao:bb7f2mf) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/cab0b37a1acdfffd7393a47ce27285e0c15e05ca/utils/slack_notifications.py#L281)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

done
___
*[`utils/slack_notifications.py` line 283 at r2](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/2#-O5OEktU8g0q-Kfm7GGs:-O5TMDGu5rS-9d5yD_Nb:b-vlkycj) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/cab0b37a1acdfffd7393a47ce27285e0c15e05ca/utils/slack_notifications.py#L283)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

do we need args.testing and args.channel?
could we say if args.channel = egg-test then add the Testing :test_tube: flag
</blockquote></details>

yeah I have removed the testing flag and updated the code to check the channel.
___
*[`utils/slack_notifications.py` line 299 at r2](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/2#-O5NYZqv7y4UR8nFL5FT:-O5TQn_BA7ZQvkslGk5f:b-7ql1td) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/cab0b37a1acdfffd7393a47ce27285e0c15e05ca/utils/slack_notifications.py#L299)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

typo successfully
</blockquote></details>

fixed
___
*[`utils/slack_notifications.py` line 308 at r4](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/2#-O5Ocsj5Eal8NL7vQz5o:-O5TQpYR9yWd5NjQpmSH:b-7ql1td) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/d4e50cf4fc7cb08977bf29b13cb3da38f1634ae9/utils/slack_notifications.py#L308)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

fixed

**Review by kjwinfield — APPROVED** [review]
> Reviewed 1 of 5 files at r5, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/2)* status: all files reviewed, 2 unresolved discussions (waiting on @RSWilson1)

___
*[`main.nf` line 36 at r6](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/2#-O5YjnQiC7oE_YuT13e9:-O5YjnQiC7oE_YuT13eA:bb7phvt) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/2954a26c43c0913929a41b20ebad4eb2d94574b6/main.nf#L36)):*
> ```Nextflow
>     if (params.testing == true) {
>         // This if block is conditional on the success of the script (cmd).
>         // Otherwise the else raisies a failure message.
> ```

typo

**Review by kjwinfield — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/2)* status: all files reviewed, 1 unresolved discussion (waiting on @RSWilson1)

**Review by RSWilson1 — COMMENTED** [review]
I'm happy with the line lengths PEP8 wise, unless there are any you want me to change.

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/2#-:-O5YlcblA8JMeZ0VYPpf:bu94pyl)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @kjwinfield)

___
*[`main.nf` line 36 at r6](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/2#-O5YjnQiC7oE_YuT13e9:-O5YlaBf9Jg17HC3VMZp:b-skfoai) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/2954a26c43c0913929a41b20ebad4eb2d94574b6/main.nf#L36)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

typo
</blockquote></details>

silly me, fixed

**Review by kjwinfield — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/2)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RSWilson1)

**Pull request merged**
