### PR TITLE
Smaller docker

### PR DESCRIPTION
**Pull request by RSWilson1**
This PR makes some minor changes to:
- Reduces size of docker.
- Updates slack notification text to make a bit clearer.

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/3)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/3)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @RSWilson1)

___
*[`.dockerignore` line 2 at r1](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/3#-O5r6CsxE3P_CVtVtiob:-O5r6CsxE3P_CVtVtioc:b9oji7n) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/a458ba334d888438929aceec9f1d3424946c5a37/.dockerignore#L2)):*
> ```ignore
> # ignore everything except for the required files to run, stops any erroneous config / output files
> # being bundled in the built image
> ```

to ignore everything you need this line: https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/92f0cd28abd6868c86dc7d00fd0e0d7491209179/.dockerignore#L3

then explicitly allow things, which I think is what you're trying to do here right? doing this still includes any other random files you might have in the same dir
___
*[`dockerfile` line 9 at r1](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/3#-O5r6eJw4QuhkagM1d7D:-O5r6eJw4QuhkagM1d7E:bn37n1n) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/a458ba334d888438929aceec9f1d3424946c5a37/dockerfile#L9)):*
> ```
>     bzip2-devel \
>     openssl-devel \
>     libffi-devel \
> ```

do you need the devel pacakges? especially openssl when you also install openssl11?



_Code quote:_
```
    bzip2-devel \
    openssl-devel \
    libffi-devel \
```
___
*[`dockerfile` line 27 at r1](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/3#-O5r6sVB0j8k7K_Xqwr2:-O5r6sVB0j8k7K_Xqwr3:bqislk4) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/a458ba334d888438929aceec9f1d3424946c5a37/dockerfile#L27)):*
> ```
> # Install pyenv and python 3.10.10
> RUN yum swap openssl-devel openssl11-devel -y && \
>     git clone https://github.com/pyenv/pyenv.git /pyenv && \
> ```

cloning the whole pyenv repo I assume will bring all other branches etc, might be better wget the specific release and untar it to install from



_Code quote:_
```
git clone https://github.com/pyenv/pyenv.git
```
___
*[`dockerfile` line 50 at r1](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/3#-O5r73g8DOTxldv5Rvog:-O5r73g8DOTxldv5Rvoh:b-5hhtjn) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/a458ba334d888438929aceec9f1d3424946c5a37/dockerfile#L50)):*
> ```
> 
> # Clone the variant_workbook_parser repository and install its dependencies
> RUN git clone --depth 1 --branch $(git ls-remote --tags --refs --sort="v:refname" https://github.com/eastgenomics/variant_workbook_parser.git | tail -n1 | sed 's/.*\///') \
> ```

again here, might be better to pin a specific release version instead of cloning (although I assume its a tiny repo)



_Code quote:_
```
RUN git clone --depth 1 --branch $(git ls-remote --tags --refs --sort="v:refname" https://github.com/eastgenomics/variant_workbook_parser.git | tail -n1 | sed 's/.*\///') \
```

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/3)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @RSWilson1)

___
*[`dockerfile` line 17 at r1](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/3#-O5r9X0h681bVRbXZHHA:-O5r9X0h681bVRbXZHHB:b8u5s4a) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/a458ba334d888438929aceec9f1d3424946c5a37/dockerfile#L17)):*
> ```
>     yum -y clean all && \
>     rm -fr /var/cache && \
>     rm -rf /var/cache/yum
> ```

doing `rm -rf /var/cache` feels extreme and other things might want to keep cached files.

I'd recommend only having `rm -rf /var/cache/yum` to clean up what is cached by yum since that won't be needed, and also to move this to the end of the Dockerfile to clear up the cache from other yum commands below. Having a quick look in the image it looks like you have still a good chunk there:

```
bash-4.2# du -sh /var/cache/yum/x86_64/2/amzn2-core/
349M	/var/cache/yum/x86_64/2/amzn2-core/
```



_Code quote:_
```
    rm -fr /var/cache && \
    rm -rf /var/cache/yum
```

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/3)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @RSWilson1)

___
*[`dockerfile` line 27 at r1](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/3#-O5r6sVB0j8k7K_Xqwr2:-O5rBVaP52m7huwXV75b:b-llks0m) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/a458ba334d888438929aceec9f1d3424946c5a37/dockerfile#L27)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

cloning the whole pyenv repo I assume will bring all other branches etc, might be better wget the specific release and untar it to install from
</blockquote></details>

actually since you install this you could just rm the `/pyenv` dir after

**Review by RSWilson1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/3)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @jethror1 and @RSWilson1)

___
*[`.dockerignore` line 2 at r1](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/3#-O5r6CsxE3P_CVtVtiob:-O5rQKPI-9diYbklDwLh:b-886gsx) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/a458ba334d888438929aceec9f1d3424946c5a37/.dockerignore#L2)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

to ignore everything you need this line: https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/92f0cd28abd6868c86dc7d00fd0e0d7491209179/.dockerignore#L3

then explicitly allow things, which I think is what you're trying to do here right? doing this still includes any other random files you might have in the same dir
</blockquote></details>

Fixed
___
*[`dockerfile` line 9 at r1](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/3#-O5r6eJw4QuhkagM1d7D:-O5rQNq71ntUtelMFl25:b64xf7m) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/a458ba334d888438929aceec9f1d3424946c5a37/dockerfile#L9)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

do you need the devel pacakges? especially openssl when you also install openssl11?
</blockquote></details>

rm openssl-devel as not needed but left the other packages as this led to errors for installing python.
___
*[`dockerfile` line 17 at r1](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/3#-O5r9X0h681bVRbXZHHA:-O5rQYOx9NudEN8ztFmd:b-31wdiu) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/a458ba334d888438929aceec9f1d3424946c5a37/dockerfile#L17)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

doing `rm -rf /var/cache` feels extreme and other things might want to keep cached files.

I'd recommend only having `rm -rf /var/cache/yum` to clean up what is cached by yum since that won't be needed, and also to move this to the end of the Dockerfile to clear up the cache from other yum commands below. Having a quick look in the image it looks like you have still a good chunk there:

```
bash-4.2# du -sh /var/cache/yum/x86_64/2/amzn2-core/
349M	/var/cache/yum/x86_64/2/amzn2-core/
```
</blockquote></details>

Yep, just kept  rm -rf /var/cache/yum also added it lower. I think by using in each instance it helps keep individual layers smaller helping reduce overall size.
___
*[`dockerfile` line 27 at r1](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/3#-O5r6sVB0j8k7K_Xqwr2:-O5rQz3q0QrFAiE-ua1H:b-559rmv) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/a458ba334d888438929aceec9f1d3424946c5a37/dockerfile#L27)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

actually since you install this you could just rm the `/pyenv` dir after
</blockquote></details>

changed to use tar.gz. The pyenv/ is where the python3.10.10 is stored.
___
*[`dockerfile` line 50 at r1](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/3#-O5r73g8DOTxldv5Rvog:-O5rgOe62KE4xw_MX9J1:b-my1iup) ([raw file](https://github.com/eastgenomics/automated-clinvar-submission/blob/a458ba334d888438929aceec9f1d3424946c5a37/dockerfile#L50)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

again here, might be better to pin a specific release version instead of cloning (although I assume its a tiny repo)
</blockquote></details>

This ensures we get the latest release of variant workbook but depth=1 should reduce the size of the clone

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-clinvar-submission/3)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RSWilson1)

**Pull request merged**
